### ISSUE TITLE
Update book repo URL to xaod_usage

### ISSUE THREAD

**Issue by matthewfeickert** [gordonwatts/xaod_usage#12]
At the moment if someone clicks the source repository button from the drop down menu under the GitHub icon on the Jupyter book

[![github_icon](https://user-images.githubusercontent.com/5142394/155943884-25881f13-27e2-4d1c-b9e1-d24deabaa6b3.png)](https://gordonwatts.github.io/xaod_usage/)

they will get sent back to the Jupyter Book project repo (https://github.com/executablebooks/jupyter-book) as that's what's currently set in the `_config.yml`

https://github.com/gordonwatts/xaod_usage/blob/7b6a00bb559c0e041a9c8047767906199a07e5f3/book/_config.yml#L24

It would be more helpful if this section of the config

https://github.com/gordonwatts/xaod_usage/blob/7b6a00bb559c0e041a9c8047767906199a07e5f3/book/_config.yml#L23-L26

became

```yaml
repository:
  url: https://github.com/gordonwatts/xaod_usage  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
```
